FROM node:18-bullseye

WORKDIR /unacademy/backend

ENV DATABASE_URL=""
ENV LIVEKIT_URL=""
ENV LIVEKIT_API_KEY=""
ENV LIVEKIT_API_SECRET=""
ENV JWT_SECRET=""
ENV AWS_ACCESS_KEY_ID=""
ENV AWS_SECRET_ACCESS_KEY=""

COPY ./backend/package*.json ./

RUN npm install
RUN npm install -g pm2

COPY ./backend ./

RUN npx prisma generate

EXPOSE 3000

RUN npm run build

CMD ["pm2-runtime", "start", "dist/index.js"]