FROM node:18-bullseye

WORKDIR /app/websocket

ENV JWT_SECRET=""

COPY ./ws/package*.json ./

RUN npm install
RUN npm install -g pm2

COPY ./ws/ ./

EXPOSE 8080

RUN npm run build

CMD ["pm2-runtime", "start", "dist/index.js"]