name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: puneetnj/unacademy-backend:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=puneetnj/unacademy-backend:latest
          cache-to: type=inline,mode=max
          secrets: |
            DATABASE_URL: "${{ secrets.DATABASE_URL }}"
            LIVEKIT_URL: "${{ secrets.LIVEKIT_URL }}"
            LIVEKIT_API_KEY: "${{ secrets.LIVEKIT_API_KEY }}"
            LIVEKIT_API_SECRET: "${{ secrets.LIVEKIT_API_SECRET }}"
            JWT_SECRET: "${{ secrets.JWT_SECRET }}"
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Verify Backend Image
        run: |
          docker pull puneetnj/unacademy-backend:latest
          docker image inspect puneetnj/unacademy-backend:latest

  deploy-websocket:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Websocket Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.websocket
          push: true
          tags: puneetnj/unacademy-websocket:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=puneetnj/unacademy-websocket:latest
          cache-to: type=inline,mode=max

      - name: Verify Websocket Image
        run: |
          docker pull puneetnj/unacademy-websocket:latest
          docker image inspect puneetnj/unacademy-websocket:latest
